name: yukimi
description: Anime/Manga command-line interface backed up by Tenka.
version: 1.0.0

publish_to: none

environment:
    sdk: ">=2.15.0-226.0.dev <3.0.0"

dependencies:
    args: ^2.3.0
    collection: ^1.15.0
    colorize: ^3.0.0
    dl: ^1.0.5
    extensions:
        git:
            url: git://github.com/yukino-app/packages.git
            ref: extensions
    http: ^0.13.4
    path: ^1.8.0
    shlex: ^2.0.2
    utilx:
        git:
            url: git://github.com/yukino-app/packages.git
            ref: utilx
    utilx_desktop:
        git:
            url: git://github.com/yukino-app/packages.git
            ref: utilx_desktop

dev_dependencies:
    devx:
        git:
            url: git://github.com/yukino-app/packages.git
            ref: devx
    lint: ^1.5.3
